### ISSUE TITLE
Handle ASS on multiple lines

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#297]
Hello.

I installed AnimeOpenings on my server with a karaoke database we run. Setting it up was pretty easy and we generated a names.php from our database just fine. Thank you lots for making this.

I have several little issues though related to subtitles, I'll post them and this is the first one.

On videos where there is supposed to be several subtitles lines at the same time (the lyrics are quite fast) lyrics are overlapping each other. Would it be possible to handle multiple lines when one isn't completed yet?

Sample video : http://live.karaokes.moe/?video=%20Opening%20-JAP%20-%20DuckTales%20%282017%29%20

Here's the ASS file : 
https://lab.shelter.moe/karaokemugen/karaokebase/blob/master/lyrics/JAP%20-%20DuckTales%20(2017)%20-%20OP%20-%20DuckTales.ass

Thanks for reading this :)

**Comment by AxelTerizaki** [comment]
Well, apparently links don't work because the names are too long >.>  But loading the .ass file I provided on any video should do the trick anyway.

**Comment by AxelTerizaki** [comment]
Isn't it possible to detect this when loading the ASS script? It won't change during runtime, so maybe figuring out in advance on which line putting which dialogue event could be doable.

```Dialogue: 0,0:00:00.78,0:00:05.56,1920X1080,,0,0,0,fx,{\fade(255,0,255,0,850,4680,4780)\k100}{\k100}{\k29}ki{\k36}ra{\k36}ku {\k30}ni {\k58}tsu{\k22}ppa{\k23}shi{\k24}re{\k10}
Dialogue: 0,0:00:03.44,0:00:08.04,1920X1080,,0,0,0,fx,{\fade(255,0,255,0,850,4500,4600)\k100}{\k100}{\k49}i{\k76}tsu{\k49}de{\k66}mo{\k10}
```

These two lines for example overlap since line 1's end time is after line 2's beginning time. 

It might be a bit too simple though and there could be caveats I can't seem to think about right now...

**Comment by Yay295** [comment]
I think most of your subtitles are on the top line, so commit 59caaf22ecdf9b1c649221f03efad3b310bf54a6 should I think handle them. There's still a lot of optimizations and improvements I can do, but this should get you started.

**Comment by Yay295** [comment]
(╯°□°）╯︵ ┻━┻

I'm not seeing the first syllable issue though.

**Comment by Yay295** [comment]
Okay, *now* it should work.

**Comment by AxelTerizaki** [comment]
Not terribly better :p 

I don't get the syllabe issue anymore but it's hard to tell as as soon as the second line begins, the subtitle layout suddenly gets reduced and it produces garbage and stops rendering anything new

![firefox_2018-08-23_23-55-01](https://user-images.githubusercontent.com/4531597/44554155-27a20b00-a730-11e8-8022-64369659998e.png)

**Comment by AxelTerizaki** [comment]
![firefox_2018-08-23_23-57-22](https://user-images.githubusercontent.com/4531597/44554198-55874f80-a730-11e8-9b4f-b340c395862c.png)

I enabled Stylus again to show you how I see that it resized the part where it draws subtitles.

**Comment by Yay295** [comment]
Alright, that issue should be fixed now.

**Comment by Yay295** [comment]
The first-syllable bug is a different issue, since it appears before any collisions happen.

**Comment by AxelTerizaki** [comment]
Yep, I'll make a separate issue for that later.

Though, I git pulled and it doesn't seem to solve anything regarding any collisions though. Example : https://live.karaokes.moe/?video=%20Ending%20-JAP%20-%20Boku%20no%20Kanojo%20ga%20Majimesugiru%20Sho-bitch%20na%20Ken%20 

Subs are still on top of each other instead of being on different line when there are two lines at the same time on screen.

**Comment by Yay295** [comment]
Alright, it's actually definitely working now. https://openings.moe/Yay295/test/?video=Opening1-AokiHaganeNoArpeggio%3AArsNova

I think I might know what caused the other issue too, but I haven't checked yet.

**Comment by AxelTerizaki** [comment]
Yeah, it works perfect now! Thank you so much! 

I noticed another weird behaviour unrelated to this, I'll open another issue to show you.

I'll close this one in the meantime. Should I open one for the first syllabe thing?

**Comment by Yay295** [comment]
Yes please.
